package io.sqlinsight.core.context;

import io.sqlinsight.core.model.QueryInfo;

public class QueryContextTracker {

    /**
     * Walks the stack trace to determine the primary source class and method 
     * causing the SQL execution based on common application layer naming conventions.
     * @param info QueryInfo object to populate
     */
    public static void populateSource(QueryInfo info) {
        StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();

        for (StackTraceElement element : stackTrace) {
            String className = element.getClassName();
            String lowerClass = className.toLowerCase();

            // Heuristic filtering for repository, service, or controller layers
            if (lowerClass.contains("repository") || 
                lowerClass.contains("service") || 
                lowerClass.contains("controller") ||
                lowerClass.contains("dao")) {

                // Exclude proxy classes commonly generated by Spring/Hibernate (e.g., CGLIB)
                if (!className.contains("$$") && !className.contains("CGLIB")) {
                    info.setSourceClass(className);
                    info.setSourceMethod(element.getMethodName());
                    return;
                }
            }
        }
    }
}
